carts/urls.py
from django.conf.urls import url

from orders.views import OrderFormView, thank
from .views import CartCreateView

urlpatterns = [
    url(r'^$', CartCreateView.as_view(), name='create_cart'),
    url(r'^order/$', OrderFormView.as_view(), name='order'),
    url(r'^order/thank/$', thank, name='thank'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from newsletter.views import home, contacts, delivery, actions, about

urlpatterns = [
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^contacts/$', contacts, name='contacts'),
    url(r'^about/$', about, name='about'),
    url(r'^delivery/$', delivery, name='delivery'),
    url(r'^actions/$', actions, name='actions'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^menu/', include('products.urls')),
    url(r'^cart/', include('carts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from datetime import datetime

from django.db import models

from enumfields import EnumField, Enum

from products.models import Product


class PickupPoint(models.Model):
    name = models.CharField('Точка выдачи', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Точка выдачи'
        verbose_name_plural = 'Точки выдачи'


class Order(models.Model):
    class Delivery(Enum):
            SELF = 1
            COURIER = 2
            class Labels:
                SELF = 'Самовывоз'
                COURIER = 'Курьерская доставка'

    class Payment(Enum):
        CASH = 1
        CARD = 2
        class Labels:
            CASH = 'Наличными'
            CARD = 'Картой курьеру'

    delivery = EnumField(Delivery, verbose_name='Способ самовывоза')
    pikup_point = models.ForeignKey(PickupPoint, verbose_name='Точка выдачи', blank=True, null=True,
                                    on_delete=models.SET_NULL)
    name = models.CharField('Имя', max_length=100)
    street = models.CharField('Улица', max_length=255, blank=True, null=True)
    house = models.CharField('Дом', max_length=50, blank=True, null=True)
    apartment = models.CharField('Номер', max_length=50, blank=True, null=True)
    phone = models.CharField('Телефон', max_length=30)
    payment = EnumField(Payment, verbose_name = 'Способы оплаты')
    money = models.PositiveSmallIntegerField('Сдача с суммы', default=0, blank=True, null=True)
    count = models.PositiveSmallIntegerField('Укажите количество человек', default=1)
    comment = models.TextField('Комментарий', blank=True)
    full_price = models.DecimalField('Цена за заказ', max_digits=7, decimal_places=2)
    full_weight = models.IntegerField('Вес всего заказа, гр.')
    created = models.DateTimeField('Дата создания', default=datetime.now)
    checked = models.BooleanField('Обработан?', default=False)

    def __str__(self):
        return 'Заказ на %s от %s' % (self.name, self.created)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderPorduct(models.Model):
    order = models.ForeignKey(Order, verbose_name='Заказ', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField('Название', max_length=100)
    price = models.DecimalField('Цена', max_digits=7, decimal_places=2)
    full_price = models.DecimalField('Цена за все продукты', max_digits=7, decimal_places=2)
    weight = models.IntegerField('Вес, гр.')
    full_weight = models.IntegerField('Вес продуктов, гр.')
    quantity = models.PositiveSmallIntegerField('Количество')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Продукты в заказе'
        verbose_name_plural = 'Продукты в заказах'

products/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    image = models.ImageField(u'Фото категории', upload_to='category/')
    subimage = models.ImageField(u'Картинка под фото', upload_to='category/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категория продуктов'
        verbose_name_plural = 'Категории продуктов'


class Product(models.Model):
    title = models.CharField('Название', max_length=100)
    slug = models.CharField(max_length=100, unique=True)
    price = models.DecimalField('Цена', max_digits=7, decimal_places=2)
    sale_price = models.DecimalField('Цена со скидкой', max_digits=7, decimal_places=2, blank=True, null=True)
    composition = models.TextField('Состав')
    weight = models.IntegerField('Вес, гр.')
    calorie = models.IntegerField('Калорийность, ккал')
    protein = models.IntegerField('Белков')
    carbohydrate = models.IntegerField('Углеводов')
    fat = models.IntegerField('Жиров')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField('Традиция блюда')
    image = models.ImageField('Фото', upload_to='products/', null=True)
    image_small = models.ImageField('Маленькое фото', upload_to='products/', null=True)
    show_main = models.BooleanField('На главную страницу', default=False)
    recomendations = models.ManyToManyField('self', verbose_name='Рекомендуемые продукты', blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', args=(self.slug,))

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

templates/new/_cart_products.html
<div class="row cart-calc">
  <div class="col-12 col-sm-6 col-md-4 col-xl-12">
    <ul class="cart-orders">
      {% for product, count, price in products_info %}
        <li class="cart-orders-item">
          <span class="cart-orders-item__name">{{ forloop.counter }}. {{ product }}</span>
          <div class="cart-orders-item__count">
          <div class="number-input">
            <button type="button" class="quantity-down"></button>
            <input class="quantity" min="0" name="quantity" value="{{ count }}" type="number" data-id="{{ product.pk }}">
            <button type="button" class="quantity-up plus"></button>
          </div>
          <span class="cart-orders-item__price">{{ price|floatformat:0 }}&nbsp;р</span>
          </div>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>
<div class="row cart-calc">
  <div class="col-12">
    <div class="cart-total">
      <div class="cart-total__total">
        <!--<span>Итого:</span>-->
        <!--&nbsp;--><b>{{ products_info|length }} блюда</b>&nbsp;
        <small><b>{{ full_weight }} гр.</b></small>
      </div>
      <div class="cart-total__pay"><span>К оплате:</span>&nbsp;<b>{{ full_sum|floatformat:0 }} &#8381;</b></div>
    </div>
  </div>
</div>

templates/new/_menu.html
<nav id="menu">{% load static %}
  <div>
    <div class="cart">
      <div class="cart__header">
        <button class="cart__close"><i class="fas fa-times"></i></button>
        <div class="cart__shop-cart active{% if products_info %} not-empty{% endif %}"><img src="{% static 'img/shopping-cart-black.svg' %}" alt="Shopping cart black"></div>Ваш заказ:
      </div>
      <div class="cart__content">
        <div class="cart__body">
          <form class="cart-form" action="{% url 'order' %}" id="order" method="post">{% csrf_token %}
            <input type="hidden" name="url" value="{{ request.path }}">
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
              </ul>
            {% endif %}
            {% include 'new/_cart_products.html' %}
            <div class="row">
              <div class="col-sm-6 col-md-4 col-xl-12 order-sm-2 order-md-2 order-xl-1">
                <div class="cart-delivery-methods cart-item">
                  <h6 class="cart-item__title">Способ доставки:</h6>
                  <div class="cart-form-grid">
                    <div class="cart-form-group">
                      <div class="custom-control custom-radio">
                        <input type="radio" id="radio-pickup" name="{{ form.delivery.html_name }}" value="1" class="custom-control-input" checked>
                        <label class="custom-control-label" for="radio-pickup">Самовывоз</label>
                      </div>
                    </div>
                    <div class="pickup">
                      {% for point in form.pikup_point.field.queryset.all %}
                      <div class="cart-form-group">
                        <div class="custom-control custom-radio">
                          <input type="radio" id="radio-item-pickup-{{ point.pk }}" name="{{ form.pikup_point.html_name }}" value="{{ point.pk }}" class="custom-control-input"{% if forloop.counter == 1 %} checked{% endif %}>
                          <label class="custom-control-label" for="radio-item-pickup-{{ point.pk }}">{{ point }}</label>
                        </div>
                      </div>
                      {% endfor %}
                    </div>
                    <div class="cart-form-group">
                    <div class="custom-control custom-radio">
                      <input type="radio" id="radio-express-delivery" name="{{ form.delivery.html_name }}" value="2" class="custom-control-input">
                      <label class="custom-control-label" for="radio-express-delivery">Курьерская доставка</label>
                    </div>
                    </div>
                    <div class="express-delivery">
                      <div class="cart-form-group">
                        <input class="cart-form-control" name="street" placeholder="Улица:">
                      </div>
                      <div class="cart-form-group">
                        <input class="cart-form-control" name="apartment" placeholder="Дом:">
                      </div>
                      <div class="cart-form-group">
                        <input class="cart-form-control" name="house" placeholder="Квартира:">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="cart-contacts cart-item">
                  <h6 class="cart-item__title">Контакты для связи:</h6>
                  <div class="cart-form-grid">
                    <div class="cart-form-group">
                    <input class="cart-form-control" name="name" placeholder="Имя:" required>
                    </div>
                    <div class="cart-form-group">
                    <input id="cart-phone" class="cart-form-control" name="phone" placeholder="Телефон:" required>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-12 col-md-4 col-xl-12 order-sm-1 order-md-1 order-xl-2">
                <div class="cart-pay cart-item">
                  <h6 class="cart-item__title">Способы оплаты:</h6>
                  <div class="cart-form-grid">
                    <div class="cart-form-group">
                    <div class="custom-control custom-radio">
                      <input type="radio" id="radio-in-cash" name="{{ form.payment.html_name }}" value="1" class="custom-control-input" checked>
                      <label class="custom-control-label" for="radio-in-cash"><img src="{% static 'img/purse.png' %}" alt="Наличными">Наличными</label>
                    </div>
                    </div>
                    <div class="cash">
                    <div class="cart-form-group">
                      <div class="custom-control custom-radio">
                        <input type="radio" id="radio-cash" name="cash" value="no-change" class="custom-control-input" checked>
                        <label class="custom-control-label" for="radio-cash">Без сдачи</label>
                      </div>
                    </div>
                    <div class="cart-form-group">
                      <div class="custom-control custom-radio">
                        <input type="radio" id="radio-with-change" name="cash" value="with-change" class="custom-control-input">
                        <label class="custom-control-label" for="radio-with-change">Со сдачей, с суммы</label>
                      </div>
                    </div>
                    <div class="cart-form-group">
                      <input class="cart-form-control" name="money" id="id_money">
                    </div>
                    </div>
                    <div class="cart-form-group">
                    <div class="custom-control custom-radio">
                      <input type="radio" id="radio-credit-card" name="{{ form.payment.html_name }}" value="2" class="custom-control-input">
                      <label class="custom-control-label" for="radio-credit-card"><img src="{% static 'img/card.png' %}" alt="Картой курьеру">Картой курьеру</label>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 col-md-4 col-xl-12 order-sm-3 order-md-3 order-xl-3">
                <div class="cart-appliances cart-item">
                  <h6 class="cart-item__title">Приборы:</h6>
                  <div class="cart-form-grid">
                    <div class="cart-form-group">
                    <input class="cart-form-control" name="count" placeholder="Укажите кол-во человек" value="1" type="number" required>
                    </div>
                  </div>
                </div>
                <div class="cart-comments cart-item">
                  <h6 class="cart-item__title">Комментарии:</h6>
                  <div class="cart-form-grid">
                    <div class="cart-form-group">
                    <textarea class="cart-form-control" rows="4" name="comment"></textarea>
                    <span class="min-order">Минимальный заказ 500р</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class="cart__footer">
          <button type="submit" class="btn cart__btn" form="order">Заказать</button>
        </div>
      </div>
    </div>
  </div>
</nav>

templates/new/about-us.html
{% extends 'new/base.html' %}

{% load solo_tags static %}

{% get_solo 'newsletter.Config' as config %}

{% block content %}
  <section id="s-about-us-preview" class="s-about-us-preview">
      <div class="about-us-preview__item" style="background-image: url({% static 'img/bg-about-us.jpg' %});">
        <div class="container">
          <div class="about-us-preview__content">
              <img src="{% static 'img/logo.png' %}" alt="Logo" class="about-us-preview__logo">
              <h2 class="about-us-preview__title">{{ config.about_header1 }}</h2>
              <p class="about-us-preview__desc">{{ config.about_header2 }}</p>
          </div>
        </div>
      </div>
  </section>

  <section class="s-about-us">
    <div class="container">
      <div class="s-title">
        <hr>
        <h2>{{ config.about_header3 }}</h2>
        <hr>
      </div>
      {{ config.about_content|safe }}
      <div class="d-flex justify-content-center">
        <a href="{% url 'product_list' %}" class="btn">Перейти в меню</a>
      </div>
    </div>
  </section>

  <a href="#s-about-us-preview" class="arrow-up d-none d-md-flex" rel='m_PageScroll2id'><i class="fas fa-arrow-up"></i></a>
{% endblock %}

templates/new/contacts.html
{% extends 'new/menu_base.html' %}
{% load static solo_tags %}

{% get_solo 'newsletter.Config' as config %}

{% block content %}
  <div id="content" class="container">
    <div class="row">
      <div class="col-xl-9 col-lg-12">
        <section id="s-contacts" class="s-contacts">
          <div class="container">
            <div class="s-title">
              <hr>
              <h2>Контакты</h2>
              <hr>
            </div>
            {% if messages %}
              <ul class="messages">
                  {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
                  {% endfor %}
              </ul>
            {% endif %}
            <div class="row justify-content-center">
              <div class="col-lg-3 col-md-4 order-2 order-md-1">
              <div class="contact-item">
                <h5 class="contact-item__title">Контактный email</h5>
                <a href="mailto:{{ config.contact_email }}" class="contact-item__link">{{ config.contact_email }}</a>
              </div>
              </div>
              <div class="col-lg-3 col-md-4 order-1 order-md-2">
              <div class="contact-item">
                <h5 class="contact-item__title">Служба поддержки</h5>
                <a href="tel:{{ config.phone_raw }}" class="contact-item__link">{{ config.phone_formatted }}</a>
                <small>Будние дни {{ config.work_time }}</small>
              </div>
              </div>
              <div class="col-lg-3 col-md-4 order-3 order-md-3">
              <div class="contact-item">
                <h5 class="contact-item__title">Служба поддержки</h5>
                <span class="contact-item__work">{{ config.work_support_weekday }}</span>
                <span class="contact-item__work">{{ config.work_support_weekend }}</span>
              </div>
              </div>
            </div>
            <div class="contact-form">
              <form class="row justify-content-center" action="{% url 'contacts' %}" method="post">{% csrf_token %}
                <div class="col-10 d-flex justify-content-center">
                  <h4 class="contact-form__title">Напишите нам</h4>
                </div>
                <div class="col-md-5">
                  <div class="contact-form__group">
                  <input type="text" class="contact-form__control" placeholder="Ваше имя" name="full_name" required>
                  </div>
                  <div class="contact-form__group">
                  <input type="text" class="contact-form__control" placeholder="Ваш телефон" name="phone" required>
                  </div>
                  <div class="contact-form__group">
                  <input type="email" class="contact-form__control" placeholder="Ваш email" name="email" required>
                  </div>
                </div>
                <div class="col-md-5">
                  <div class="contact-form__group">
                  <textarea class="contact-form__control" placeholder="Текс сообщения" name="message" required></textarea>
                  </div>
                  <div class="contact-form__group">
                  <i class="fas fa-link"></i>
                  <input id="add-file" type="file" class="contact-form__control" name="document">
                  <label for="add-file">Прикрепить документ</label>
                  </div>
                </div>
                <div class="col-10 d-flex justify-content-center">
                  <button type="submit" class="btn contact-form__btn">Отправить</button>
                </div>
              </form>
            </div>
          </div>
        </section>
        <section id="map" class="s-map" style="height: 500px;"></section>
      </div>
      <div class="col-xl-3 d-xl-block d-lg-none">
        <div class="fix-cart">

        </div>
      </div>
    </div>
  </div>
  <a href="#s-contacts" class="arrow-up d-none d-md-flex" rel='m_PageScroll2id'><i class="fas fa-arrow-up"></i></a>
{% endblock %}

{% block js %}
  <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=babad61d-3cc3-4040-9c17-05d0b1ab0c60" type="text/javascript"></script>
  <script>
    ymaps.ready(function () {

      var imgSizes = [160, 215];

      if (window.innerWidth < 576) {
      imgSizes = [80, 110];
      }

    var myMap = new ymaps.Map('map', {
      center: [55.751574, 37.573856],
      zoom: 15,
      controls: []
      }),

      myPlacemark = new ymaps.Placemark(myMap.getCenter(), {
        hintContent: 'КишМиш'
      }, {
        iconLayout: 'default#image',
        iconImageHref: 'img/marker-map.png',
        iconImageSize: imgSizes,
        iconImageOffset: [-5, -38]
      })

      myMap.geoObjects.add(myPlacemark);
      myMap.behaviors.disable('scrollZoom');
    });
  </script>
  <style>
    [class*="ymaps-2"][class*="-ground-pane"] {
      filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");
      /* Firefox 3.5+ */
      -webkit-filter: grayscale(100%);
      /* Chrome 19+ & Safari 6+ */
    }
  </style>
{% endblock %}

templates/new/menu.html
{% extends 'new/menu_base.html' %}
{% load static pytils_translit cart_tags %}

{% block content %}
  <div id="content" class="container">
    <div class="row">
      <div class="col-xl-9 col-lg-12">
        <div class="product-inner__list">
          <section id="s-menu" class="s-menu">
            <div class="s-title">
              <h2>Меню:</h2>
            </div>
            <ul class="menu-list">
              {% for category in categories %}
                <li class="menu-item"><a href="#{{ category.title|translify }}" class="menu-item__link __mPS2id _mPS2id-h mPS2id-clicked" rel="m_PageScroll2id" data-ps2id-offset="120">
                  <span class="menu-item__icon"></span>{{ category.title }}</a>
                </li>
              {% endfor %}
            </ul>
          </section>
          {% for category in categories %}
            <section id="{{ category.title|translify }}" class="s-products">
              <div class="s-title">
                <hr>
                <h2>{{ category.title }}</h2>
                <hr>
              </div>
              <div class="row">
                {% for product in category.product_set.all %}
                  <div class="col-6 col-md-4 col-sm-6">
                    <a onclick=" $('html, body').animate({scrollTop: 0},0);"  class="popular-dishes" data-dish-id="dish-popup-{{ product.pk }}">
                      <img class="popular-dishes__img img-responsive" src="{{ product.image_small.url }}" alt="Плов куриный">
                      <h5 class="popular-dishes__name">{{ product.title }}</h5>
                      <div class="popular-dishes__count">
                        <div class="number-input">
                          <button class="quantity-down"></button>
                          <input class="quantity" min="0" name="quantity" value="{% current_count product %}" type="number" data-id="{{ product.pk }}">
                          <button class="quantity-up plus"></button>
                        </div>
                        <span class="popular-dishes__price">{{ product.price|floatformat:0 }} р</span>
                      </div>
                      <p class="popular-dishes__desc">{{ product.description }}</p>
                    </a>
                  </div>
                {% endfor %}
              </div>
            </section>
          {% endfor %}
        </div>
        {% for category in categories %}
          {% for product in category.product_set.all %}
            <div id="dish-popup-{{ product.pk }}" class="dish-popup">
              <div class="dish">
                <div class="dish__control">
                  <a href="{% url 'product_list' %}#{{ product.category|translify }}" class="dish__close__with__name"><< <span>{{ product }}</span></a>
                  <a href="{% url 'product_list' %}#{{ product.category|translify }}" class="dish__close"><i class="fas fa-times"></i></a>
                </div>
                <div class="dish__head">
                  <img src="{{ product.image.url }}" alt="Dish">
                  <div class="dish__main-info">
                    <h2 class="dish__name">{{ product }}</h2>
                    <span class="dish__weight">{{ product.weight }} гр.</span>
                    <div class="dish__count">
                      <span class="dish__price">{{ product.price|floatformat:0 }}&nbsp;р</span>
                      <div class="number-input">
                        <button type="button" class="quantity-down"></button>
                        <input class="quantity" min="0" name="quantity" value="{% current_count product %}" type="number" data-id="{{ product.pk }}">
                        <button type="button" class="quantity-up plus"></button>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="dish__mobile-info d-md-none">
                  <ul class="dish-composition-list">
                    <li class="dish-composition-item">
                      <span>{{ product.calorie }}</span><span>ккал</span>
                    </li>
                    <li class="dish-composition-item">
                      <span>{{ product.protein }}</span><span>белки</span>
                    </li>
                    <li class="dish-composition-item">
                      <span>{{ product.carbohydrate }}</span><span>углеводы</span>
                    </li>
                    <li class="dish-composition-item">
                      <span>{{ product.fat }}</span><span>жиры</span>
                    </li>
                  </ul>
                </div>
                <div class="dish__content">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="dish-composition">
                        <h4 class="dish-composition__title">Состав:</h4>
                        <p class="dish-composition__desc">{{ product.composition }}</p>
                        <ul class="dish-composition-list d-none d-md-flex">
                          <li class="dish-composition-item">
                            <span>{{ product.calorie }}</span><span>ккал</span>
                          </li>
                          <li class="dish-composition-item">
                            <span>{{ product.protein }}</span><span>белки</span>
                          </li>
                          <li class="dish-composition-item">
                            <span>{{ product.carbohydrate }}</span><span>углеводы</span>
                          </li>
                          <li class="dish-composition-item">
                            <span>{{ product.fat }}</span><span>жиры</span>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="dish-traditions">
                        <h4 class="dish-traditions__title">Традиция блюда:</h4>
                        <p class="dish-traditions__desc">{{ product.description }}</p>
                      </div>
                    </div>
                  </div>
                </div>
  <!--              <div class="dish__footer">-->
  <!--                <button class="btn dish__btn" data-id="{{ product.pk }}">-->
  <!--                  <span>В корзину</span>-->
  <!--                  <span>{{ product.price|floatformat:0 }} р</span>-->
  <!--                </button>-->
  <!--              </div>-->
              </div>
              {% if product.recomendations.all %}
                <div class="dish-recom-block">
                  <div class="s-title">
                    <hr>
                    <h2>Рекомендации к блюду</h2>
                    <hr>
                  </div>
                  <div class="dish-recom-grid">
                    <div class="row">
                      {% for rel_product in product.recomendations.all %}
                      <div class="col-6">
                        <a onclick=" $('html, body').animate({scrollTop: 0},0);"  class="popular-dishes" data-dish-id="dish-popup-{{ rel_product.pk }}">
                          <div class="dish-recom">
                            <div class="dish-recom__img">
                              <img src="{{ rel_product.image_small.url }}" alt="{{ rel_product }}">
                            </div>
                            <div class="dish-recom__body">
                              <div class="dish-recom__head">
                                <h2 class="dish-recom__name">{{ rel_product }}</h2>
                                <span class="dish-recom__weight">{{ rel_product.weight }} гр.</span>
                              </div>
                              <p class="dish-recom__desc">{{ rel_product.description }}</p>
                              <div class="dish-recom__footer">
                                <div class="dish-recom__count">
                                  <span class="dish-recom__price">{{ rel_product.price }}&nbsp;р</span>
                                  <div class="number-input">
                                    <button type="button" class="quantity-down"></button>
                                    <input class="quantity" min="0" name="quantity" value="{% current_count rel_product %}" type="number" data-id="{{ rel_product.pk }}">
                                    <button type="button" class="quantity-up plus"></button>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </a>
                      </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              {% endif %}
            </div>
          {% endfor %}
        {% endfor %}
      </div>
      <div class="col-xl-3 d-xl-block d-lg-none">
        <div id="fix-cart" class="fix-cart">

        </div>
      </div>
    </div>
  </div>

  <a href="#content" class="arrow-up d-none d-md-flex" rel='m_PageScroll2id'><i class="fas fa-arrow-up"></i></a>
{% endblock %}

templates/new/order_email.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Новый заказ с сайта</title>
</head>
<body>
<h1>Новый заказ с сайта</h1>
<p>ФИО: {{ order.name }}</p>
<p>Тел.: {{ order.phone }}</p>
<p>Способ самовывоза: {{ order.get_delivery_display }}
  {% if order.delivery == order.Delivery.SELF %}
    ({{ order.pikup_point }})
  {% else %}
  ({{ order.street }}, д. {{ order.house }}, кв {{ order.apartment }})
  {% endif %}</p>
<p>Способы оплаты: {{ order.get_payment_display }} {% if order.payment == order.Payment.CASH and order.money %}необходима сдача с суммы {{ order.money }}{% endif %}</p>
<p>Количество человек: {{ order.count }}</p>
<table>
  <tr>
    <th>Продукт</th>
    <th>Цена за еденицу</th>
    <th>Вес за еденицу</th>
    <th>Количество</th>
    <th>Цена</th>
    <th>Вес</th>
  </tr>
  <tr>
    {% for product in order.orderproduct_set.all %}
      <td>{{ product.title }}</td>
      <td>{{ product.price }}</td>
      <td>{{ product.weight }}</td>
      <td>{{ product.quantity }}</td>
      <td>{{ product.full_price }}</td>
      <td>{{ product.full_weight }}</td>
    {% endfor %}
  </tr>
</table>
</body>
</html>